// <auto-generated />
using System;
using Facturation.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FacturationNew.Shared.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20210126160030_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Facturation.Shared.ChiffreAffaire", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("chiffreAffairesDu")
                        .HasColumnType("float");

                    b.Property<double>("chiffreAffairesReel")
                        .HasColumnType("float");

                    b.Property<string>("year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ChiffreAffaire");

                    b.HasData(
                        new
                        {
                            id = 1,
                            chiffreAffairesDu = 66666.0,
                            chiffreAffairesReel = 66666.0
                        });
                });

            modelBuilder.Entity("Facturation.Shared.Facture", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ChiffreAffaireid")
                        .HasColumnType("int");

                    b.Property<string>("client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateEmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateReglement")
                        .HasColumnType("datetime2");

                    b.Property<double>("montantDu")
                        .HasColumnType("float");

                    b.Property<double>("montantRegle")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("ChiffreAffaireid");

                    b.ToTable("Facture");

                    b.HasData(
                        new
                        {
                            id = 3,
                            client = "John Test",
                            code = "F666",
                            dateEmission = new DateTime(2021, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dateReglement = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            montantDu = 666.0,
                            montantRegle = 0.0
                        });
                });

            modelBuilder.Entity("Facturation.Shared.Facture", b =>
                {
                    b.HasOne("Facturation.Shared.ChiffreAffaire", null)
                        .WithMany("listFac")
                        .HasForeignKey("ChiffreAffaireid");
                });

            modelBuilder.Entity("Facturation.Shared.ChiffreAffaire", b =>
                {
                    b.Navigation("listFac");
                });
#pragma warning restore 612, 618
        }
    }
}
